ads/urls.py
from django.urls import path

from . import views


app_name = 'ads'


urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),
    # Picture
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    # Comment
    path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad_comment_delete'),
]

# we use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

authz/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'authz'

urlpatterns = [
    path('', TemplateView.as_view(template_name='authz/main.html')),
    path('open', views.OpenView.as_view(), name='open'),
    path('manual', views.ManualProtect.as_view(), name='manual'),
    path('protect', views.ProtectView.as_view(), name='protect'),
]

mystie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('ads/', include('ads.urls')),
    path('cats/', include('cats.urls')),
    path('autos/', include('autos.urls')),
    path('authz/', include('authz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hello/', include('hello.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

authz/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.utils.http import urlencode

# Create your views here.
class OpenView(View):

    def get(self, request):
        return render(request, 'authz/main.html')


class ManualProtect(View):

    def get(self, request):
        if not request.user.is_authenticated:
            loginurl = reverse('login')+'?'+urlencode({'next': request.path})
            return redirect(loginurl)

        return render(request, 'authz/main.html')


class ProtectView(LoginRequiredMixin, View):

    def get(self, request):
        return render(request, 'authz/main.html')

authz/templates/authz/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base Login</title>
</head>
<body>
{% block content %}{% endblock %}
</body>
</html>

authz/templates/authz/main.html
{% extends "authz/base.html" %}


{% block content %}

<h1>Current request.path: {{ request.path }}</h1>

{% if user.is_authenticated %}

<p>
    Authenticated as:
    <ul>
        <li>Name: {{ user.get_full_name }}</li>
        <li>Email: {{ user.email }}</li>
        <li>Id: {{ user.id }}</li>
    </ul>
</p>
<p>You can <a href="{% url 'logout' %}?next={% url 'authz:open' %}">Logout</a></p>

{% else %}

<p>You are not logged in</p>
<p>You can <a href="{% url 'login' %}?next={{ request.path }}">Login</a> if you like.</p>

{% endif %}

<ul>
    <li>
        Go to <a href="{% url 'authz:open' %}">{% url 'authz:open' %}</a> (no login required)
    </li>
    <li>
        Go to <a href="{% url 'authz:manual' %}">{% url 'authz:manual' %}</a> (protected by user.is_authenticated)
    </li>
    <li>
        Go to <a href="{% url 'authz:protect' %}">{% url 'authz:protect' %}</a> (protected by LoginRequiredMixin)
    </li>
</ul>

{% endblock content %}