ads/urls.py
from django.urls import path

from . import views


app_name = 'ads'


urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),
    # Picture
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    # Comment
    path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad_comment_delete'),
]

# we use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

cats/urls.py
from django.urls import path
from django.views.generic import TemplateView

from . import views

app_name = 'cats'

urlpatterns = [
    path('', views.MainView.as_view(), name='all'),
    path('main/create/', views.CatCreate.as_view(), name='cat_create'),
    path('main/<int:pk>/update/', views.CatUpdate.as_view(), name='cat_update'),
    path('main/<int:pk>/delete/', views.CatDelete.as_view(), name='cat_delete'),
    path('lookup/', views.BreedView.as_view(), name='breed_list'),
    path('lookup/create/', views.BreedCreate.as_view(), name='breed_create'),
    path('lookup/<int:pk>/update/', views.BreedUpdate.as_view(), name='breed_update'),
    path('lookup/<int:pk>/delete/', views.BreedDelete.as_view(), name='breed_delete'),    
]

mystie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('ads/', include('ads.urls')),
    path('cats/', include('cats.urls')),
    path('autos/', include('autos.urls')),
    path('authz/', include('authz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hello/', include('hello.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

cats/models.py
from django.db import models
from django.core.validators import MinLengthValidator

# Create your models here.

class Breed(models.Model):

    name = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Breed must be greater than 1 character")]
    )


    def __str__(self):
        return self.name


class Cat(models.Model):
    nickname = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Nickname must be greater than 1 character")]
    )
    weight = models.PositiveIntegerField()
    foods = models.CharField(max_length=300)
    breed = models.ForeignKey('Breed', on_delete=models.CASCADE, null=False)


    def __str__(self):
        return self.nickname

cats/forms.py
from django.forms import ModelForm

from cats.models import Cat, Breed


class BreedForm(ModelForm):
    class Meta:
        model = Breed
        fields = '__all__'


class CatForm(ModelForm):
    class Meta:
        model = Cat
        fields = '__all__'

cats/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views import View
from django.urls import reverse_lazy

from cats.models import Cat, Breed
from cats.forms import CatForm, BreedForm

# Create your views here.



class MainView(LoginRequiredMixin, View):

    def get(self, request):
        bc = Breed.objects.all().count()
        cl = Cat.objects.all()

        ctx = {'breed_count': bc, 'cat_list': cl}

        return render(request, 'cats/cat_list.html', ctx)


class BreedView(LoginRequiredMixin, View):

    def get(self, request):
        bl = Breed.objects.all()
        ctx = {'breed_list': bl}

        return render(request, 'cats/breed_list.html', ctx)


class BreedCreate(LoginRequiredMixin, View):
    template = 'cats/breed_form.html'
    success_url = reverse_lazy('cats:all')


    def get(self, request):
        form = BreedForm()
        ctx = {'form': form}

        return render(request, self.template, ctx)


    def post(self, request):
        form = BreedForm(request.POST)

        if not form.is_valid():
            ctx = {'form': form}

            return render(request, self.template, ctx)

        form.save()
        return redirect(self.success_url)




class BreedUpdate(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/breed_form.html'



    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(instance=breed)
        ctx = {'form': form}
        return render(request, self.template, ctx)

    
    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        form = BreedForm(request.POST, instance=breed)

        if not form.is_valid():
            ctx = {'form': form}

            return render(request, self.template, ctx)


        form.save()
        return redirect(self.success_url)


class BreedDelete(LoginRequiredMixin, View):
    model = Breed
    success_url = reverse_lazy('cats:all')
    template = 'cats/breed_confirm_delete.html'

    
    def get(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        ctx = {'breed': breed}

        return render(request, self.template, ctx)


    def post(self, request, pk):
        breed = get_object_or_404(self.model, pk=pk)
        breed.delete()
        
        return redirect(self.success_url)


class CatCreate(LoginRequiredMixin, View):

    template = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:all')

    def get(self, request):
        form = CatForm()
        ctx = {'form': form}

        return render(request, self.template, ctx)


    def post(self, request):
        form = CatForm(request.POST)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)


        form.save()
        return redirect(self.success_url)


class CatUpdate(LoginRequiredMixin, View):

    model = Cat
    template = 'cats/cat_form.html'
    success_url = reverse_lazy('cats:all')


    def get(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        form = CatForm(instance=cat)
        ctx = {'form': form}

        return render(request, self.template, ctx)


    def post(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        form = CatForm(request.POST, instance=cat)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)


        form.save()
        return redirect(self.success_url)


class CatDelete(LoginRequiredMixin, View):

    model = Cat
    template = 'cats/cat_confirm_delete.html'
    success_url = reverse_lazy('cats:all')

    def get(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        ctx = {'cat': cat}

        return render(request, self.template, ctx)


    def post(self, request, pk):
        cat = get_object_or_404(self.model, pk=pk)
        cat.delete()

        return redirect(self.success_url)

cats/templates/cats/breed_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}
<h1>Delete Breed</h1>

<p>Are you sure you want to delete the make: {{ breed }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>
{% endblock %}

cats/templates/cats/breed_form.html
{% extends "base_bootstrap.html" %}

{% block content %}
<h1>Create Breed</h1>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
    </form>
{% endblock %}

cats/templates/cats/breed_list.html
{% extends "base_bootstrap.html" %}


{% block content %}

<h1>Breed List</h1>

{% if breed_list %}

<ul>
    {% for breed in breed_list %}
    <li>
        {{ breed.name }}
        ( <a href="{% url 'cats:breed_update' breed.id %}">Update</a> | <a href="{% url 'cats:breed_delete' breed.id %}">Delete</a> )
    </li>
    <br>
    {% endfor %}
</ul>
{% else %}
    <p>There are no breeds in the library.</p>
{% endif %}

<p><a href="{% url 'cats:breed_create' %}">Add a breed</a></p>
<p><a href="{% url 'cats:all' %}">Back to Cat List</a></p>



{% endblock %}

cats/templates/cats/cat_confirm_delete.html
{% extends "base_bootstrap.html" %}


{% block content %}
<h1>Delete a Cat</h1>
<p>Are you sure you want to delete the cat: {{ cat.nickname }}?</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>
{% endblock %}

cats/templates/cats/cat_form.html
{% extends "base_bootstrap.html" %}


{% block content %}
<h1>Add Cat</h1>
<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
        <input type="submit" value="Submit">
        <input type="submit" onclick="window.location='{% url 'cats:all' %}' ; return false;" value="Cancel">
</form>
{% endblock %}

cats/templates/cats/cat_list.html
{% extends "base_bootstrap.html" %}


{% block content %}

<h1>Cat List</h1>

{% if cat_list %}

<ul>
    {% for cat in cat_list %}
    <li>
        {{ cat.nickname }} {{ cat.breed }}
        ( <a href="{% url 'cats:cat_update' cat.id %}">Update</a> | <a href="{% url 'cats:cat_delete' cat.id %}">Delete</a> ) <br>
        {{ cat.foods }} ( {{ cat.weight }} ponds)
    </li>
    <br>
    {% endfor %}
</ul>

{% else %}
    <p>There are no cats in the bakery.</p>
{% endif %}

<p>
    {% if breed_count > 0 %}
        <a href="{% url 'cats:cat_create' %}">Add a cat</a>
    {% else %}
        Please add a breed before you add a cat
    {% endif %}
</p>

<p>
    <a href="{% url 'cats:breed_list' %}">View breeds</a> ( {{ breed_count }} ) | <a href="{% url 'cats:breed_create' %}">Add  a breed</a>
</p>


{% endblock %}