ads/urls.py
from django.urls import path

from . import views


app_name = 'ads'


urlpatterns = [
    path('', views.AdListView.as_view(), name='all'),
    path('ad/<int:pk>', views.AdDetailView.as_view(), name='ad_detail'),
    path('ad/create', views.AdCreateView.as_view(), name='ad_create'),
    path('ad/<int:pk>/update', views.AdUpdateView.as_view(), name='ad_update'),
    path('ad/<int:pk>/delete', views.AdDeleteView.as_view(), name='ad_delete'),
    # Picture
    path('pic_picture/<int:pk>', views.stream_file, name='pic_picture'),
    # Comment
    path('ad/<int:pk>/comment', views.CommentCreateView.as_view(), name='ad_comment_create'),
    path('comment/<int:pk>/delete', views.CommentDeleteView.as_view(), name='ad_comment_delete'),
]

# we use reverse_lazy in urls.py to delay looking up the view until all the paths are defined

mystie/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path('ads/', include('ads.urls')),
    path('cats/', include('cats.urls')),
    path('autos/', include('autos.urls')),
    path('authz/', include('authz.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('hello/', include('hello.urls')),
    path('', TemplateView.as_view(template_name='home/main.html')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
]

ads/models.py
from django.db import models
from django.core.validators import MinLengthValidator
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.

class Ad(models.Model):

    title = models.CharField(
        max_length=200,
        validators=[MinLengthValidator(2, "Title must be greater than 2 characters")]
    )
    price = models.DecimalField(max_digits=7, decimal_places=2, null=True)
    text = models.TextField()
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    # Picture
    picture = models.BinaryField(null=True, editable=True)
    content_type = models.CharField(max_length=256, null=True, help_text='The MIMEType of the file')
    # -------

    # Comment
    comments = models.ManyToManyField(settings.AUTH_USER_MODEL, through='Comment', related_name='comments_owned')
    # -------

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.title

class Comment(models.Model):
    text = models.TextField(validators=[MinLengthValidator(3, "Comment must be greater than 3 characters")])

    ad = models.ForeignKey(Ad, on_delete=models.CASCADE)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    # Shows up in the admin list
    def __str__(self):
        if len(self.text) < 15:
            return self.text

        return self.text[:11] + ' ...'

ads/forms.py
from django import forms
from django.core.files.uploadedfile import InMemoryUploadedFile

from ads.models import Ad
from ads.humanize import natural_size


class CreateForm(forms.ModelForm):

    # 2 MB max picture size
    max_upload_limit = 2 * 1024 * 1024
    max_upload_limit_text = natural_size(max_upload_limit)


    # Call this 'picture' so it gets copied from the form to the in-memory model
    # It will not be the "bytes", it will be the "InMemoryUploadedFile"
    # because we need  to pull out things like content_type
    picture = forms.FileField(required=False, label='File to Upload <= ' + max_upload_limit_text)
    upload_field_name = 'picture'


    class Meta:
        model = Ad
        fields = ['title', 'price', 'text', 'picture'] # Picture is manual


    # Validate the size of the picture
    def clean(self):
        cleaned_data = super().clean()
        pic = cleaned_data.get('picture')

        if pic is None:
            return
        if len(pic) > self.max_upload_limit:
            self.add_error('picture', "File must be < " + self.max_upload_limit_text + " bytes")


    def save(self, commit=True):
        instance = super(CreateForm, self).save(commit=False)

        # We only need to adjust picture if it is a freshly uploaded file
        f = instance.picture # make a copy

        if isinstance(f, InMemoryUploadedFile): # Extract data from the form to the model
            byte_arr = f.read()
            instance.content_type = f.content_type
            instance.picture = byte_arr # Overwrite withe the actual image data


        if commit:
            instance.save()

        return instance



# https://docs.djangoproject.com/en/3.0/topics/http/file-uploads/
# https://stackoverflow.com/questions/2472422/django-file-upload-size-limit
# https://stackoverflow.com/questions/32007311/how-to-change-data-in-django-modelform
# https://docs.djangoproject.com/en/3.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other



# strip means to remove whitespace from the begining and the end before storing the column
class CommentForm(forms.Form):
    comment = forms.CharField(required=True, max_length=500, min_length=3, strip=True)

ads/views.py
from django.views import View
from django.urls import reverse, reverse_lazy
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.files.uploadedfile import InMemoryUploadedFile


from ads.models import Ad, Comment
from ads.owner import OwnerListView, OwnerDetailView, OwnerCreateView, OwnerUpdateView, OwnerDeleteView
from ads.forms import CreateForm, CommentForm

# Create your views here.


class AdListView(OwnerListView):
    model = Ad
    template_name = "ads/ads_list.html"


class AdDetailView(OwnerDetailView):
    model = Ad
    template_name = "ads/ad_detail.html"

    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk)
        comments = Comment.objects.filter(ad=ad).order_by('-updated_at')
        comment_form = CommentForm()
        context = {'ad': ad, 'comments': comments, 'comment_form': comment_form}

        return render(request, self.template_name, context)


class AdCreateView(LoginRequiredMixin, View):
    model = Ad
    # fields = ['title', 'price', 'text']

    template_name = "ads/ad_form.html"
    success_url = reverse_lazy('ads:all')


    def get(self, request, pk=None):
        form = CreateForm()
        ctx = {'form': form}
        return render(request, self.template_name, ctx)

    
    def post(self, request, pk=None):
        form = CreateForm(request.POST, request.FILES or None)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)


        # Add ownder to the model before saving
        ad = form.save(commit=False)
        ad.owner = self.request.user
        ad.save()
        return redirect(self.success_url)


class AdUpdateView(LoginRequiredMixin, View):
    model = Ad
    # fields = ['title', 'price', 'text']

    template_name = "ads/ad_form.html"
    success_url = reverse_lazy('ads:all')


    def get(self, request, pk):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(instance=ad)
        ctx = {'form': form}
        return render(request, self.template_name, ctx)


    def post(self, request, pk=None):
        ad = get_object_or_404(Ad, id=pk, owner=self.request.user)
        form = CreateForm(request.POST, request.FILES or None, instance=ad)

        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template_name, ctx)

        ad = form.save(commit=False)
        ad.save()

        return redirect(self.success_url)

class AdDeleteView(OwnerDeleteView):
    model = Ad

    template_name = "ads/ad_confirm_delete.html"
    success_url = reverse_lazy('ads:all')


class CommentCreateView(LoginRequiredMixin, View):

    def post(self, request, pk):
        ad = get_object_or_404(Ad, id=pk)
        comment = Comment(text=request.POST['comment'], owner=request.user, ad=ad)
        comment.save()
        return redirect(reverse('ads:ad_detail', args=[pk]))

class CommentDeleteView(OwnerDeleteView):
    model = Comment
    template_name = "ads/comment_confirm_delete.html"

    def get_success_url(self):
        ad = self.object.ad
        return reverse('ads:ad_detail', args=[ad.id])


def stream_file(request, pk):
    ad = get_object_or_404(Ad, id=pk)
    response = HttpResponse()
    response['Content-Type'] = ad.content_type
    response['Content-Length'] = len(ad.picture)
    response.write(ad.picture)
    return response

ads/templates/ads/ad_confirm_delete.html
{% extends "base_menu.html" %}

{% block content %}

<h1>Delete Ad</h1>

<p>Are you sure you want to delete the ad: {{ ad }}</p>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete.">
    <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}' ; return false;">
</form>

{% endblock %}

ads/templates/ads/ad_detail.html
{% extends "base_menu.html" %}
{% load humanize %} 

{% block head %}
<style>
.overlay
{
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    z-index: 10;
    display: none;
    background-color: rgba(0, 0, 0, 0.5); /* dim the background */
}
</style>
{% endblock %}

{% block content %}

{% if ad.content_type %}

<div id="overlay" class="overlay" style="text-align: center;" onclick="document.getElementById('overlay').style.display='none';">
    <img src="{% url 'ads:pic_picture' ad.id %}" style="width: 90%; margin-top: 50px; border: 3px solid black;">
</div>

{% endif %}

<h1>Ad Detail</h1>
<span style="float: right;">

( {{ ad.updated_at|naturaltime }} )
{% if ad.owner == user %}
<a href="{% url 'ads:ad_update' ad.id %}"><i class="fa fa-pencil"></i>Update</a>
<a href="{% url 'ads:ad_delete' ad.id %}"><i class="fa fa-trash">Delete</i></a>
{% endif %}

</span>

<h1>{{ ad.title }}</h1>

{% if ad.content_type %}

<img src="{% url 'ads:pic_picture' ad.id %}" style="float: right; max-width: 50%;" onclick="document.getElementById('overlay').style.display='block';">

{% endif %}

<p>{{ ad.text }}</p>
<p>{{ ad.price }}</p>

<p><a href="{% url 'ads:all' %}">All Ads</a></p>


{% if user.is_authenticated %}

<br clear="all">
<p>
    {% load crispy_forms_tags %}
    <form action="{% url 'ads:ad_comment_create' ad.id %}" method="POST">
        {% csrf_token %}
        {{ comment_form|crispy }}
    <input type="submit" value="Submit">
    <input type="submit" value="All Ads" onclick="window.location.href='{% url 'ads:all' %}'; return false;">
    </form>
</p>

{% endif %}

{% for comment in comments %}
<p>
    {{ comment.text }} ( {{ comment.updated_at|naturaltime }} )
    {% if user == comment.owner %}
    <a href="{% url 'ads:ad_comment_delete' comment.id %}"><i class="fa fa-trash"></i></a>
    {% endif %}
</p>

{% endfor %}

{% endblock %}

ads/templates/ads/ad_form.html
{% extends "base_menu.html" %}
{% load crispy_forms_tags %}

{% block content %}
<h1>Create Ad</h1>
<p>
    <form action="" method="POST" id="upload_from" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form|crispy }}
        <input type="submit" value="Submit">
        <input type="submit" value="Cancel" onclick="window.location.href='{% url 'ads:all' %}' ; return false;">
    </form>
</p>

<script>
    $("#upload_from").submit(function() 
    {
        console.log('Checking file size');
        if (window.File && window.FileReader && window.FileList && window.Blob)
        {
            var file = $('#id_{{ form.upload_field_name }}')[0].files[0];
            if (file && file.size > {{ form.max_upload_limit }})
            {
                alert("File " + file.name + " of type " + file.type + " must be < {{ form.max_upload_limit_text }}");
                return false
            }
        }
    }
    );
</script>

{% endblock %}

ads/templates/ads/ad_list.html
{% extends "base_menu.html" %}

{% block content %}

<h1>Ads List</h1>

<p>
    {% if ad_list %}
    <ul>
        {% for ad in ad_list %}
        <li>
            <a href="{% url 'ads:ad_detail' ad.id %}">{{ ad.title }}</a>
            {% if ad.owner == user %}
            ( <a href="{% url 'ads:ad_update' ad.id %}">Edit</a> | <a href="{% url 'ads:ad_delete' ad.id %}">Delete</a> )
            {% endif %}
        </li>
        <br>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no ads in the database.</p>
    {% endif %}
</p>

<p>
    <a href="{% url 'ads:ad_create' %}">Add an Ad</a>
    {% if user.is_authenticated %}
    | <a href="{% url 'logout' %}?next={% url 'ads:all' %}">Logout</a>
    {% else %}
    | <a href="{% url 'login' %}?next={% url 'ads:all' %}">Login</a>
    {% endif %}
</p>

{% endblock %}

ads/templates/ads/comment_confirm_delete.html
{% extends "base_bootstrap.html" %}

{% block content %}

<h1>Delete Comment</h1>
<p>Are you sure you want to delete:</p>
<p>{{ comment.text }}</p>


<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-primary" value="Yes, delete.">
    <a href="{% url 'ads:ad_detail' comment.ad.id %}" class="btn btn-secondary">Cancel</a>
</form>


{% endblock %}